services:
  mongo:
    image: mongo:7.0.9
    restart: always
    env_file:
      - ".env"
    volumes:
      - mongo_data:/data/db
    ports:
      - "0.0.0.0:27017:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s

volumes:
  mongo_data:
